### ISSUE TITLE
morphir-sdk-core v0.11.0 not published to maven

### ISSUE THREAD

**Issue by nwokafor-choongsaeng** [finos/morphir-jvm#137]
**Describe the bug**
`morphir-sdk-core v0.11.0` was not published to maven. The last publish for `morphir-sdk-core` was 2 years ago whereas `morphir-sdk-spark` and `morphir-sdk-json` was last published 15 days ago.

**Comment by AttilaMihaly** [comment]
As it turns out these modules are actually being published it's just difficult to find them because Maven shows and older version which was published by accident with a very high version number. Unfortunately those cannot be removed from Maven Central because deleting is not allowed. 

The workaround is to look for the specific version that matches the latest morphir-jvm GitHub release.
